USE [IHRIS]
SELECT COLUMN_NAME,* 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'HR' AND TABLE_SCHEMA='dbo'


SELECT 'iHRIS' AS 'Program', 'HR' AS 'Table', [COLUMN_NAME] AS Element 
FROM [IHRIS].[dbo].INFORMATION_SCHEMA.COLUMNS